FROM python:3.7-slim
RUN apt-get -yqq update && apt-get install -yqq g++ libopenblas-base libopenblas-dev swig
ENV G2P_MODEL_DIR=/app/fairseq_g2p/
WORKDIR /app
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY . /app
VOLUME /app/final.mdl

